trigger:
  - master
  - develop
  - release/*
  - egypt-master-merge
  - merge-master

pr:
  - master
  - develop
  - merge-master

resources:
  repositories:
    - repository: templates
      type: git
      name: Core/build-templates

stages:
  - stage: Build
    displayName: Build
    jobs:
      - template: job-build-springboot-jar.yaml@templates
        parameters:
          VeracodeAppName: 'MOB'