trigger:
  - master
  - develop

pr:
  - master
  - develop

resources:
  repositories:
    - repository: templates
      type: git
      name: Core/build-templates

stages:
  - stage: Build
    displayName: Build
    jobs:
      - template: job-build-springboot-jar.yaml@templates
    parameters:
            VeracodeAppName: 'MOB'