server:
  port: 8067
  http2:
    enabled: on
  compression:
    enabled: on
    mime-types: text/html,text/xml,text/plain,text/css, application/javascript, application/json
    min-response-size: 1024

springdoc:
  api-docs.enabled: on

spring:
  profiles.active: local
  main.lazy-initialization: false
  datasource:
    url: ${MSSQL_DEV_URL:jdbc:sqlserver://localhost:1433;databaseName=MOB-LOCAL}
    username: ${MSSQL_DEV_USERNAME:SA}
    password: ${MSSQL_DB_KEY:Asdasdasd123}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate

external:
  error-code:
    mapper:
      accounts:
        detailCallErrorMap:
          ACC-ESB-001: SEND_EMPTY_RESPONSE
          ACC-ESB-65: EXCEEDS_WITHDRAWL_FREEQUENCY
          ACC-ESB-61: EXCEEDS_WITHDRAWL_LIMIT
      otp:
        detailcallErrorMap:
          VERIFY_OTP_4003: INVALID_SESSION_TOKEN
          VERIFY_OTP_10020: OTP_VERIFIVATION_FAILED
          VERIFY_OTP_10200: MAX_OTP_ATTEMPTS_EXCEEDED
          VERIFY_OTP_10403: MAX_OTP_FAILED_ATTEMPTS_EXCEEDED
          VERIFY_OTP_USSM_100: FAILED_TO_VERIFY_OTP
          VERIFY_OTP_USSM_101: NOT_FOUND_USER_IN_DB
          VERIFY_OTP_USSM_102: USER_BLOCKED_STATUS
          VERIFY_OTP_USSM_103: USER_INACTIVE_STATUS
  fees-code:
    mapper:
      fees:
        cardLessCashFees: '0'
  otp-code:
    mapper:
       otp:
         dpPublicKey: 1
         dpRandomNumber: 1234


logging.level:
  ROOT: warn
  # org.hibernate.type.descriptor.sql: trace
  com.mashreq: debug


app:
  local:
    currency: 'AED'
    transaction.code: '015'
    transfer.product.id: 'DBLC'
  uae:
    address: 'UNITED ARAB EMIRATES'
    iban:
      length: 23
  bank:
    code: '033'
  services:
    maintenance: ${MAINTENANCE_SERVICE_URL:https://digital-dev.mashreq.com/api/maintenance-service}
    customers: ${CUSTOMER_SERVICE_URL:http://localhost:8083}
    accounts: ${ACCOUNT_SERVICE_URL:https://digital-dev.mashreq.com/api/accounts-service}
    otp: http://digital-dev.mashreq.com/api/ms-security-iam/
    cards: ${CARD_SERVICE_URL:http://cards-service:8080}
    notification: ${NOTIFICATION_SERVICE:http://notification-service:8080}
    mobcustomer: ${MOB_CUSTOMER_SERVICE:http://localhost:8088}
    beneficiary: ${BENEFICIARY_CORE_SERVICE:https://digital-dev.mashreq.com/api/beneficiary-core-service}
    mobcommon: ${MOB_COMMON_SERVICE:https://digital-dev.mashreq.com/api/mob-common-service}

redis:
  enable: false
  write.ttl: 60
  host: localhost
  port: 6379
  timeout: 5000
  password:


mob-common:
  loggers:
    logRequest: ${HTTP_DETAILS_LOG_REQUEST:true}
    logResponse: ${HTTP_DETAILS_LOG_RESPONSE:true}
    maxResponseLength: 1000
  threadPool:
    userEventAuditTaskExecutor:
      maxPoolSize: 60
      corePoolSize: 40
      queueCapacity: 100
      keepAliveSeconds: 60
      threadNamePrefix: mob-transfer-usereventlog-pool
    generalTaskExecutor:
      maxPoolSize: 30
      corePoolSize: 20
      queueCapacity: 50
      keepAliveSeconds: 60
      threadNamePrefix: mob-transfer-general-pool
  commonUserEventDataSource:
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    jdbcUrl: ${MSSQL_EVENT_DEV_URL:jdbc:sqlserver://localhost:1433;databaseName=MOB-LOCAL}
    username: ${MSSQL_EVENT_DEV_USERNAME:SA}
    password: ${MSSQL_EVENT _DB_KEY:Asdasdasd123}
    maxPoolSize: 40
    poolName: hikari-user-events-life-pool
    minimumidletime: 600000