management.endpoints:
  health:
    ldap:
      enabled: false
  web:
    base-path: /api/actuator
    exposure.include: info

springdoc:
  api-docs:
    enabled: ${SWAGGER_ENABLED}
    path: /api-docs
  swagger-ui:
    path: /swagger

spring:
  application.name: beneficiary-core-service
  profiles.active: ${ACTIVE_PROFILE:local}
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: ${MSSQL_DEV_URL}
    username: ${MSSQL_DEV_USERNAME}
    password: ${MSSQL_DB_KEY}
    hikari:
      poolName: hikari-life-insur-db-pool
      maxPoolSize: ${MSSQL_HIKARI_MAX_POOL_SIZE:30}
      minimumConnections: ${MSSQL_HIKARI_MIN_CONNECTIONS:10}
  jpa:
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2012Dialect
        enable_lazy_load_no_trans: true
  main:
    banner-mode: 'off'
    lazy-initialization: false

esb-service:
  url: ${CDM_URL:http://172.24.70.29:7800/AllOperationsSOAP_HTTP_Service}
  app-id: ${SOAP_SERVICE_APPID:SITAPPS}
  origin-id: ${SOAP_SERVICE_ORIGINID:AE}
  channel: ${SOAP_SERVICE_USERID:MOMMUSER}
  connect-timeout: ${SOAP_SERVICE_CONNECTIONTIMEOUT:15000}
  read-timeout: ${SOAP_SERVICE_READTIMEOUT:30000}
  user-id: ${USER_ID:MOMMUSER}
  access-token: ${ACCESS_TOKEN:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX25hbWUiOiJVQlRlc3Q0QG1hc2hyZXFkZXYuY29tIiwiY2hhbm5lbCI6IjJBRUMzNjRGQTg2MUFBMDY3QkYzOTI2QjZBMUQzMTNBIiwiZW1wbG95ZWVJZCI6bnVsbCwiYnJhbmNoIjoiQUQyQTU2QUVCN0FCRjM1QjYwNEZBODI1NzdEMTVCQUEiLCJhdXRob3JpdGllcyI6WyJVYl9Vc2VyIiwiVUJfUE9XRVIiLCJSZXBvcnRpbmdHcm91cCB7ODJkYWU4MDItNmY2Ni00YTBjLTg5ODAtZDA0ZTRhNDE5OWRlfSIsIlJlcG9ydGluZ0dyb3VwIHs4NzQ0YzU2YS01YWI5LTRhODMtOTk2OS0yZWQ1ZjIxMDViYjN9IiwiVUJVQVQiXSwiZW5hYmxlZCI6dHJ1ZSwiY2xpZW50X2lkIjoiYnJhbmNocG9ydGFsIiwiYnJhbmNoQ29kZSI6IkM3MkI0RDU0OTBFNjIwRTg5NUVEQUFDNzBBOEU5NUMzIiwibmJmIjoxNTgyMjA5NjMxLCJzY29wZSI6WyJyZWFkIiwid3JpdGUiLCJpZGVudGl0eSJdLCJuYW1lIjoiNjYxOERGNENCMjhGMjNGMjNGMzI3M0NFQzZGQ0YyMjMiLCJleHAiOjE1ODIyMTY4MzEsImp0aSI6IjAxYTA3YTZjLWQzMDItNDhmMC1iNDQ2LTQwY2I0MTBlY2FhZSIsImVtYWlsIjpudWxsfQ.hnrskgfb8DuP26VVVrrFcNVRXPk3TKSjslzImlw_dtM}
  service-codes:
    fundTransfer: TFT
    ibanSearch: ${ACCUITYIBAN_SERVICE_CODE:QIBANVAL}
    routingCodeSearch: ${ACCUITYROUTING_SERVICE_CODE:QFAD}
    ifscSearch: ${IFSCSEARCH_SERVICE_CODE:QAXIFSC}
    flexRuleEngine: ${FLEXRULEENGINE_SERVICE_CODE:QRMTGW}
    quickRemitIndia: ${QUICK_REMIT_INDIA:TRTPTIN}
    quickRemitPakistan: ${QUICK_REMIT_INDIA:TRTPTPK}
    quickRemitInstaRem: ${QUICK_REMIT_INDIA:TINSRPMT}
    searchAccountDetails: ${SEARCH_ACCOUNT_DETAILS:QACCDTL}
    gpiTransactionDetails: ${GPI_TRANSACTION_DETAILS:QGPITDTL}
    swiftGpiTransactionDetails: ${SWIFT_GPI_TRANSACTION_DETAILS:QSFGPITDTL}

external:
  error-code:
    mapper:
      accounts:
        detailCallErrorMap:
          ACC-ESB-001: SEND_EMPTY_RESPONSE
          ACC-ESB-65: EXCEEDS_WITHDRAWL_FREEQUENCY
          ACC-ESB-61: EXCEEDS_WITHDRAWL_LIMIT
      otp:
        detailcallErrorMap:
          VERIFY_OTP_4003: INVALID_SESSION_TOKEN
          VERIFY_OTP_10020: OTP_VERIFIVATION_FAILED
          VERIFY_OTP_10200: MAX_OTP_ATTEMPTS_EXCEEDED
          VERIFY_OTP_10403: MAX_OTP_FAILED_ATTEMPTS_EXCEEDED
          VERIFY_OTP_USSM_100: FAILED_TO_VERIFY_OTP
          VERIFY_OTP_USSM_101: NOT_FOUND_USER_IN_DB
          VERIFY_OTP_USSM_102: USER_BLOCKED_STATUS
          VERIFY_OTP_USSM_103: USER_INACTIVE_STATUS
          VERIFY_OTP_USSM_104: FAILED_TO_DECRYPT
          VERIFY_OTP_10402: DENIED_BY_POLICY_OTP_REUSE_NOT_ALLOWED
          VERIFY_OTP_30001: OBJ_TOKENSTORE_ID_NOT_FOUND
          LOGOUT_4004: USER_SESSION_ALREADY_INVALIDATED
      deal:
        detailcallErrorMap:
          ACC-ESB-15280: RECORD_NOT_FOUND
      middleware:
        detailCallErrorMap:
          EAI-FCI-BRK-21038: TRANSFER_AMOUNT_IN_NAGATIVE
          EAI-FCI-BRK-2463: FUND_TRANSFER_FREEZED
  fees-code:
    mapper:
      fees:
        cardLessCashFees: '0'

app:
  local:
    currency: 'AED'
    transaction.code: '015'
    transfer.product.id: 'DBLC'
  uae:
    transaction.code: '096'
    country.iso: 'AE'
    currency.iso: '784'
    address: 'UNITED ARAB EMIRATES'
    iban:
      length: 23
  bank:
    code: '033'
  loyalty:
    timeInterval: 1
    smilesProductBin: 524179
  services:
    maintenance: ${MAINTENANCE_SERVICE_URL:http://maintenance-service:8080}
    customers: ${CUSTOMER_SERVICE_URL:http://customers-service:8080}
    accounts: ${ACCOUNT_SERVICE_URL:http://accounts-service:8080}
    otp: ${IAM_SERVICE_URL:http://ms-security-iam:8080}
    cards: ${CARD_SERVICE_URL:http://cards-service:8080}
    notification: ${NOTIFICATION_SERVICE:http://notification-service:8080}
    mobcustomer: ${MOB_CUSTOMER_SERVICE:http://mob-customer-service:8080}
    beneficiary: ${BENEFICIARY_CORE_SERVICE:http://beneficiary-core-service:8080}
    mobcommon: ${MOB_COMMON_SERVICE:http://mob-common-service:8080}
    omw-core: ${OMW_CORE:https://172.24.70.29:7805/omw/core}
  ftcc:
    merchantId: ${TFTCC_MERCHANT_ID:000008026734}
    terminalId: ${TFTCC_TERMINAL_ID:20091124}
    authStatus: ${TFTCC_AUTH_STATUS:A}
    amountTag: ${TFTCC_AMOUNT_TAG:TFR_AMT}
    messageThrough: ${TFTCC_MESSAGE_THROUGH:U}
    transTypeCode: ${TFTCC_TRANSFER_TYPE_CODE:FAM}
    srvCode: ${TFTCC_SERVICE_CODE:TFTCC}
    productCode: ${TFTCC_PRODUCT_CODE:PACC}
    debitAccountNo: ${TFTCC_DEBIT_ACCOUNT_NO:011099270455}
    bankReferenceNo: ${TFTCC_BANK_REFERENCE_NO:363c5a1abb}
  notification:
    email:
      AE:
        emailSubject: ${NOTIFICATION_EMAIL_SUBJECT:%s Transfer request via %s}
        sellGoldSilverSubject: ${NOTIFICATION_EMAIL_SELL_SUBJECT:You sold from %s Edge account via %s}
        buyGoldSilverSubject: ${NOTIFICATION_EMAIL_BUY_SUBJECT:Your recent investment in %s Edge account via %s}
        fromEmailName: ${EMAIL_FROM_NAME_MOB:MashreqDigital}
        fromEmailAddress: ${EMAIL_FROM_ADD_MOB:MashreqDigital@mashreq.com}
        callCenterNo: ${NOTIFICATION_EMAIL_CALL_CENTER_NO:04 424 6666}
        localFundTransfer: mt-within-own-accounts.ftl
        otherFundTransfer: mt-other-accounts.ftl
        goldSilverBuySuccess: buy-goldsilver-success.ftl
        goldSilverSellSuccess: sell-goldsilver-success.ftl
    sms:
      priority: ${NOTIFICATION_SMS_SEGMENT_CUSTOMER_PRIORITY:HIGH}
      serviceId: ${NOTIFICATION_SMS_SEGMENT_CUSTOMER_SERVICEID:91}
      callCenterNo: ${NOTIFICATION_SMS_SEGMENT_CUSTOMER_CALL_CENTER_NO:04 424 6666}
      ownAccountTransactionInitiated: ${OWN_ACCOUNT_SMS:Request received through {0} for a Fund Transfer of {1} {2} with {3}. Contact {4} if you did not initiate this.}
    push:
      ownAccountTransactionInitiated: ${OWN_ACCOUNT_PUSH:Request received through {0} for a Fund Transfer of {1} {2} with {3}. Contact {4} if you did not initiate this.}

instarem:
  rules:
    bankCodeType:
      CA:
        code: TRANSIT NUMBER
        substr-index-before-assigning-to-routing-code: 4
      IN:
        code: IFSC CODE
      GB:
        code: SORT CODE
      LK:
        code: BRANCH CODE
      AU:
        code: BSB CODE


mob-common:
  loggers:
    logRequest: ${HTTP_DETAILS_LOG_REQUEST:true}
    logResponse: ${HTTP_DETAILS_LOG_RESPONSE:true}
    maxResponseLength: 1000
  threadPool:
    userEventAuditTaskExecutor:
      maxPoolSize: ${EVENT_EXECUTOR_MAX_POOL_SIZE:30}
      corePoolSize: ${EVENT_EXECUTOR_CORE_POOL_SIZE:20}
      queueCapacity: ${EVENT_EXECUTOR_QUEUE_CAPACITY:60}
      keepAliveSeconds: ${EVENT_EXECUTOR_KEEP_ALIVE:60}
      threadNamePrefix: mob-insurance-life-usereventlog-pool
    generalTaskExecutor:
      maxPoolSize: ${GENERAL_EXECUTOR_MAX_POOL_SIZE:30}
      corePoolSize: ${GENERAL_EXECUTOR_CORE_POOL_SIZE:20}
      queueCapacity: ${GENERAL_EXECUTOR_QUEUE_CAPACITY:60}
      keepAliveSeconds: ${GENERAL_EXECUTOR_KEEP_ALIVE:60}
      threadNamePrefix: mob-insurance-life-general-pool
  commonUserEventDataSource:
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    jdbcUrl: ${MSSQL_EVENT_DEV_URL:jdbc:sqlserver://10.196.3.22:1433;databaseName=MOB-DEV}
    username: ${MSSQL_EVENT_DEV_USERNAME:Mobdbuser}
    password: ${MSSQL_EVENT_DB_KEY:Mobdbuser}
    maxPoolSize: ${MSSQL_EVENT_MAX_POOL_SIZE:40}
    poolName: hikari-user-events-life-pool
    minimumConnections: ${MSSQL_EVENT_MIN_CONNECTIONS:10}

feign:
  hystrix:
    enabled: false
  httpclient:
    enabled: true
    max-connections: ${FEIGN_MAX_CONNECTION:200}
    connection-timeout: ${FEIGN_CONNECTION_TIMEOUT:2000}

redis:
  enable: true
  write.ttl: ${REDIS_TTL:60}
  host: ${REDIS_HOST:kyc-redis}
  port: ${REDIS_PORT:6379}
  timeout: ${REDIS_TIMEOUT:5000}
  password: ${REDIS_PASSWORD:P@ssword123$}
  ssl: ${REDIS_SSL:false}

async:
  thread:
    poolName: TRANSFER-CORE-ASYNC-Pool
    maxPoolSize: ${ASYNC_THREAD_MAX_POOLSIZE:30}
    corePoolSize: ${ASYNC_THREAD_CORE_POOLSIZE:20}
    queueCapacity: ${ASYNC_THREAD_QUEUE_CAPACITY:60}
    keepAliveSeconds: ${ASYNC_THREAD_KEEP_ALIVE_SECS:60}

#error:
#  map:
#    ACCOUNT_BELONGS_TO_CIF: ignore
