server:
  port: 8067
  http2:
    enabled: on
  compression:
    enabled: on
    mime-types: text/html,text/xml,text/plain,text/css, application/javascript, application/json
    min-response-size: 1024

springdoc:
  api-docs.enabled: on

spring:
  profiles.active: local
  main.lazy-initialization: false
  datasource:
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost:1433;databaseName=MOB-LOCAL
    username: SA
    password: Asdasdasd123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate

logging.level:
  ROOT: warn
  # org.hibernate.type.descriptor.sql: trace
  com.mashreq: debug
