server:
  port: 8067
  http2:
    enabled: on
  compression:
    enabled: on
    mime-types: text/html,text/xml,text/plain,text/css, application/javascript, application/json
    min-response-size: 1024

springdoc:
  api-docs.enabled: on

spring:
  profiles.active: local
  main.lazy-initialization: false
  datasource:
    url: ${MSSQL_DEV_URL:jdbc:sqlserver://10.196.3.22:1433;databaseName=MOB-DEV}
    username: ${MSSQL_DEV_USERNAME:Mobdbuser}
    password: ${MSSQL_DB_KEY:Mobdbuser}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate


logging.level:
  ROOT: warn
  # org.hibernate.type.descriptor.sql: trace
  com.mashreq: debug


app:
  local:
    currency: 'AED'
    transaction.code: '015'
    transfer.product.id: 'DBLC'
  uae:
    address: 'UNITED ARAB EMIRATES'
    iban:
      length: 23
  bank:
    code: '033'
  services:
    maintenance: ${MAINTENANCE_SERVICE_URL:http://localhost:8085}
    customers: ${CUSTOMER_SERVICE_URL:http://localhost:8083}
    accounts: ${ACCOUNT_SERVICE_URL:http://localhost:8082}
    cards: ${CARD_SERVICE_URL:http://cards-service:8080}
    notification: ${NOTIFICATION_SERVICE:http://notification-service:8080}
    mobcustomer: ${MOB_CUSTOMER_SERVICE:http://localhost:8088}
    beneficiary: ${BENEFICIARY_CORE_SERVICE:http://localhost:8081}
    mobcommon: ${MOB_COMMON_SERVICE:http://localhost:8084}

redis:
  enable: false
  write.ttl: 60
  host: localhost
  port: 6379
  timeout: 5000
  password: