management:
  health:
    ldap:
      enabled: false
  endpoints:
    web:
      base-path: /api/actuator
      exposure.include: info

springdoc:
  api-docs:
    enabled: ${SWAGGER_ENABLED}
    path: /api-docs
  swagger-ui:
    path: /swagger

spring:
  application.name: transfer-core-service
  profiles.active: ${ACTIVE_PROFILE:dev}
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: ${MSSQL_DB_URL}
    username: ${MSSQL_DEV_USERNAME}
    password: ${MSSQL_DB_KEY}
    hikari:
      poolName: hikari-life-insur-db-pool
      maxPoolSize: ${MSSQL_HIKARI_MAX_POOL_SIZE:30}
      minimumConnections: ${MSSQL_HIKARI_MIN_CONNECTIONS:10}
  jpa:
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2012Dialect
        enable_lazy_load_no_trans: true
  main:
    banner-mode: 'off'
    lazy-initialization: false

esb-service:
  url: ${CDM_URL:http://172.24.70.29:7800/AllOperationsSOAP_HTTP_Service}
  app-id: ${SOAP_SERVICE_APPID:SITAPPS}
  origin-id: ${SOAP_SERVICE_ORIGINID:AE}
  channel: ${SOAP_SERVICE_USERID:MOMMUSER}
  connect-timeout: ${SOAP_SERVICE_CONNECTIONTIMEOUT:15000}
  read-timeout: ${SOAP_SERVICE_READTIMEOUT:30000}
  max-per-route: ${SOAP_SERVICE_MAXPERROUTE:100}
  max-connection: ${SOAP_SERVICE_MAXCONNECTION:100}
  validate-after-inactive: ${SOAP_SERVICE_VALIDATE_INACTIVE:60000}
  user-id: ${USER_ID:MOMMUSER}
  tft-user-id: ${TFT_USER_ID:MOMMUSER}
  access-token: ${ACCESS_TOKEN}
  service-codes:
    fundTransfer: TFT
    ibanSearch: ${ACCUITYIBAN_SERVICE_CODE:QIBANVAL}
    routingCodeSearch: ${ACCUITYROUTING_SERVICE_CODE:QFAD}
    ifscSearch: ${IFSCSEARCH_SERVICE_CODE:QAXIFSC}
    flexRuleEngine: ${FLEXRULEENGINE_SERVICE_CODE:QRMTGW}
    quickRemitIndia: ${QUICK_REMIT_INDIA:TRTPTIN}
    quickRemitPakistan: ${QUICK_REMIT_INDIA:TRTPTPK}
    quickRemitInstaRem: ${QUICK_REMIT_INDIA:TINSRPMT}
    searchAccountDetails: ${SEARCH_ACCOUNT_DETAILS:QACCDTL}
    gpiTransactionDetails: ${GPI_TRANSACTION_DETAILS:QGPITDTL}
    swiftGpiTransactionDetails: ${SWIFT_GPI_TRANSACTION_DETAILS:QSFGPITDTL}

external:
  error-code:
    mapper:
      accounts:
        detailCallErrorMap:
          ACC-ESB-001: SEND_EMPTY_RESPONSE
          ACC-ESB-65: EXCEEDS_WITHDRAWL_FREEQUENCY
          ACC-ESB-61: EXCEEDS_WITHDRAWL_LIMIT
      otp:
        detailcallErrorMap:
          VERIFY_OTP_4003: INVALID_SESSION_TOKEN
          VERIFY_OTP_10020: OTP_VERIFIVATION_FAILED
          VERIFY_OTP_10200: MAX_OTP_ATTEMPTS_EXCEEDED
          VERIFY_OTP_10403: MAX_OTP_FAILED_ATTEMPTS_EXCEEDED
          VERIFY_OTP_USSM_100: FAILED_TO_VERIFY_OTP
          VERIFY_OTP_USSM_101: NOT_FOUND_USER_IN_DB
          VERIFY_OTP_USSM_102: USER_BLOCKED_STATUS
          VERIFY_OTP_USSM_103: USER_INACTIVE_STATUS
          VERIFY_OTP_USSM_104: FAILED_TO_DECRYPT
          VERIFY_OTP_10402: DENIED_BY_POLICY_OTP_REUSE_NOT_ALLOWED
          VERIFY_OTP_30001: OBJ_TOKENSTORE_ID_NOT_FOUND
          LOGOUT_4004: USER_SESSION_ALREADY_INVALIDATED
      deal:
        detailcallErrorMap:
          ACC-ESB-15280: RECORD_NOT_FOUND
      middleware:
        detailCallErrorMap:
          EAI-FCI-BRK-21038: TRANSFER_AMOUNT_IN_NAGATIVE
          EAI-FCI-BRK-2463: FUND_TRANSFER_FREEZED
          EAI-FCI-BRK-998: ULTIMATE_BENEFICIARY_IBAN_NOT_VALID
          EAI-FCI-BRK-1019: MW_TRANSACTION_NOT_ALLOWED_FOR_PRODUCT
          EAI-FCI-BRK-103:  MW_INSUFFICIENT_FUND
          EAI-FCI-BRK-1070: MW_TRANSACTION_NOT_ALLOWED_FOR_TRANSACTION_CODE
          EAI-FCI-BRK-108:  MW_ACCOUNT_CLOSED
          EAI-FCI-BRK-116:  MW_RESTRICED_FOR_COUNTRY
          EAI-FCI-BRK-15401: MW_DEBIT_FAILURE_FOR_KYC
          EAI-FCI-BRK-17381:  MW_UNHANDLED_EXCEPTION
          EAI-FCI-BRK-2261: MW_FUTURE_VALUED_TRANSFER_NOT_ALLOWED
          EAI-FCI-BRK-2465: MW_ACCOUNT_NOT_MARKED_FOR_CREDIT
          EAI-FCI-BRK-31310:  MW_AMOUNT_FULLY_UTILIZED
          FT-VALS-44: EXACHANGE_RATE_AMOUNT_NOT_EQUATE
          TN-8011: FT_CC_MW_SUCCESS_FAILED_RESPONSE
  fees-code:
    mapper:
      fees:
        cardLessCashFees: '0'

app:
  auth:
    security-service-url: ${IAM_SERVICE_URL:http://ms-security-iam:8080}
  local:
    currency: ${LOCAL_CURRENCY:AED}
    transfer.product.id: 'DBLC'
    transaction.code: '096'
    country.iso: ${LOCAL_COUNTRY_ISO:AE}
    address: ${LOCAL_ADDRESS:UNITED ARAB EMIRATES}
    iban:
      length: ${IBAN_LENGTH:23}
      accountNumber: ${MASHREQ_ACCOUNTNUMBER_LENGTH:12}
    bank:
      code: ${LOCAL_BANK_CODE:033}
    tftAuthorizationCode: ${TFT_AUTHORIZATION_CODE:A}
  loyalty:
    timeInterval: 1
    smilesProductBin: 524179
  standingInstructions:
    disabled: ${STANDING_INSTRUCTIONS_DISABLED:false}
  promocode:
    disabled: ${PROMO_CODE_DISABLED:false}
  services:
    maintenance: ${MAINTENANCE_SERVICE_URL:http://maintenance-service:8080}
    customers: ${CUSTOMER_SERVICE_URL:http://customers-service:8080}
    accounts: ${ACCOUNT_SERVICE_URL:http://accounts-service:8080}
    cards: ${CARD_SERVICE_URL:http://cards-service:8080}
    notification: ${NOTIFICATION_SERVICE:http://notification-service:8080}
    mobcustomer: ${MOB_CUSTOMER_SERVICE:http://mob-customer-service:8080}
    beneficiary: ${BENEFICIARY_CORE_SERVICE:http://beneficiary-core-service:8080}
    mobcommon: ${MOB_COMMON_SERVICE:http://mob-common-service:8080}
    omw-core: ${OMW_CORE:https://172.24.70.29:7805/omw/core}
    beneficiaryservice: ${BENEFICIARY_SERVICE:http://beneficiary-service:8080}
    quick-remit: ${QUICK_REMIT_SERVICE:http://mob-quickremit-service:8080}
    bank-charges: ${BANK_CHARGES_SERVICE:http://bank-charges-service:8080}
  ftcc:
    merchantId: ${TFTCC_MERCHANT_ID:000008026734}
    terminalId: ${TFTCC_TERMINAL_ID:20091124}
    authStatus: ${TFTCC_AUTH_STATUS:A}
    amountTag: ${TFTCC_AMOUNT_TAG:TFR_AMT}
    messageThrough: ${TFTCC_MESSAGE_THROUGH:U}
    transTypeCode: ${TFTCC_TRANSFER_TYPE_CODE:FAM}
    srvCode: ${TFTCC_SERVICE_CODE:TFTCC}
    productCode: ${TFTCC_PRODUCT_CODE:PACC}
    debitAccountNo: ${TFTCC_DEBIT_ACCOUNT_NO:011099270455}
    bankReferenceNo: ${TFTCC_BANK_REFERENCE_NO:363c5a1abb}
  nonProd:
    otpRelaxed: ${OTP_RELAXED:false}
  cprRestrictions:
    enabled: ${ENABLE_CPR_CHANGES:false}
  notification:
    email:
      AE:
        emailSubject: ${NOTIFICATION_EMAIL_SUBJECT:%s Transfer request via %s}
        sellGoldSilverSubject: ${NOTIFICATION_EMAIL_SELL_SUBJECT:You sold from %s Edge account via %s}
        buyGoldSilverSubject: ${NOTIFICATION_EMAIL_BUY_SUBJECT:Your recent investment in %s Edge account via %s}
        payLaterSubject: ${PL_EMAIL_SUBJECT:Pay later request}
        StandingInstructionSubject: ${SI_EMAIL_SUBJECT:Standing instruction request}
        fromEmailName: ${EMAIL_FROM_NAME_MOB:MashreqDigital}
        fromEmailAddress: ${EMAIL_FROM_ADD_MOB:MashreqDigital@mashreq.com}
        localFundTransfer: templates/mt-within-own-accounts
        otherFundTransfer: templates/mt-other-accounts
        goldSilverBuySuccess: templates/buy-goldsilver-success
        goldSilverSellSuccess: templates/sell-goldsilver-success
        plSiFundTransfer: templates/plEmailTemplate
      EG:
        emailSubject: ${NOTIFICATION_EMAIL_SUBJECT:%s Transfer request via %s}
        payLaterSubject: ${PL_EMAIL_SUBJECT:Pay later request}
        StandingInstructionSubject: ${SI_EMAIL_SUBJECT:Standing instruction request}
        fromEmailName: ${EMAIL_FROM_NAME_MOB:MashreqDigital}
        fromEmailAddress: ${EMAIL_FROM_ADD_MOB:MashreqDigital@mashreq.com}
        localFundTransfer: templates/mt-within-own-accounts-eg
        otherFundTransfer: templates/mt-other-accounts-eg
        plSiFundTransfer: templates/plEmailTemplate-eg

    sms:
      mashreqServiceId: ${ALERT_SMS_MASHREQ_PAYMENT_SERVICEID:330}
      neoServiceId: ${ALERT_SMS_NEO_PAYMENT_SERVICEID:350}
      priority: ${NOTIFICATION_SMS_SEGMENT_CUSTOMER_PRIORITY:HIGH}
      serviceId: ${NOTIFICATION_SMS_SEGMENT_CUSTOMER_SERVICEID:91}
      callCenterNo: ${NOTIFICATION_SMS_SEGMENT_CUSTOMER_CALL_CENTER_NO:04 424 6666}
      ownAccountTransactionInitiated: ${OWN_ACCOUNT_SMS:Request received for Fund Transfer of {0} {1} with Reference number {2}. Contact {3} if you did not initiate this.}
      plSiCreation: ${PL_SI_CREATION_SMS:On your request SI/Pay later has been set up for the beneficiary {0}, account number {1}. If not requested, please contact {2}. Thank you for using our services.}
    push:
      ownAccountTransactionInitiated: ${OWN_ACCOUNT_PUSH:Request received through {0} for a Fund Transfer of {1} {2} with {3}. Contact {4} if you did not initiate this.}
      plSiCreation: ${PL_SI_CREATION_SMS:On your request SI/Pay later has been set up for the beneficiary {0}, account number {1}. If not requested, please contact {2}. Thank you for using our services.}
  countriesWhereQrDisabledForCompany: ${LIST_OF_COUNTRIES:PK}
instarem:
  rules:
    bankCodeType:
      CA:
        code: TRANSIT NUMBER
        substr-index-before-assigning-to-routing-code: 4
      IN:
        code: IFSC CODE
      GB:
        code: SORT CODE
      LK:
        code: BRANCH CODE
      AU:
        code: BSB CODE

mob-common:
  loggers:
    logRequest: ${HTTP_DETAILS_LOG_REQUEST:true}
    logResponse: ${HTTP_DETAILS_LOG_RESPONSE:true}
    maxResponseLength: 1000
  threadPool:
    userEventAuditTaskExecutor:
      maxPoolSize: ${EVENT_EXECUTOR_MAX_POOL_SIZE:30}
      corePoolSize: ${EVENT_EXECUTOR_CORE_POOL_SIZE:20}
      queueCapacity: ${EVENT_EXECUTOR_QUEUE_CAPACITY:60}
      keepAliveSeconds: ${EVENT_EXECUTOR_KEEP_ALIVE:60}
      threadNamePrefix: mob-insurance-life-usereventlog-pool
    generalTaskExecutor:
      maxPoolSize: ${GENERAL_EXECUTOR_MAX_POOL_SIZE:30}
      corePoolSize: ${GENERAL_EXECUTOR_CORE_POOL_SIZE:20}
      queueCapacity: ${GENERAL_EXECUTOR_QUEUE_CAPACITY:60}
      keepAliveSeconds: ${GENERAL_EXECUTOR_KEEP_ALIVE:60}
      threadNamePrefix: mob-insurance-life-general-pool
  commonUserEventDataSource:
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    jdbcUrl: ${MSSQL_EVENT_DB_URL}
    username: ${MSSQL_EVENT_DEV_USERNAME}
    password: ${MSSQL_EVENT_DB_KEY}
    maxPoolSize: ${MSSQL_EVENT_MAX_POOL_SIZE:40}
    poolName: hikari-user-events-life-pool
    minimumConnections: ${MSSQL_EVENT_MIN_CONNECTIONS:10}

feign:
  hystrix:
    enabled: false
  httpclient:
    enabled: true
    max-connections: ${FEIGN_MAX_CONNECTION:200}
    connection-timeout: ${FEIGN_CONNECTION_TIMEOUT:2000}

redis:
  enableRedisCache: true
  host: ${REDIS_HOST:kyc-redis}
  port: ${REDIS_PORT:6379}
  password: ${REDIS_PASSWORD:P@ssword123$}
  ssl: ${REDIS_SSL:false}
  timeout: ${REDIS_TIMEOUT:5000}
  maxTotal: ${REDIS_MAX_TOTAL:128}
  maxIdle: ${REDIS_MAX_IDLE:128}
  minIdle: ${REDIS_MIN_IDLE:16}
  minEvictableIdleTime: ${REDIS_MIN_EVICTABLE_IDLE_TIME:60}
  timeBetweenEviction: ${REDIS_TIME_BETWEEN_EVICTION_RUNS:30}
  numTestsPerEvictionRun: ${REDIS_NUM_TESTS_PER_EVICTION_RUN:3}
  writeTtl: ${REDIS_TTL:60}

async:
  thread:
    poolName: TRANSFER-CORE-ASYNC-Pool
    maxPoolSize: ${ASYNC_THREAD_MAX_POOLSIZE:30}
    corePoolSize: ${ASYNC_THREAD_CORE_POOLSIZE:20}
    queueCapacity: ${ASYNC_THREAD_QUEUE_CAPACITY:60}
    keepAliveSeconds: ${ASYNC_THREAD_KEEP_ALIVE_SECS:60}

#error:
#  map:
#    ACCOUNT_BELONGS_TO_CIF: ignore
