server:
  port: 8067
  http2:
    enabled: on
  compression:
    enabled: on
    mime-types: text/html,text/xml,text/plain,text/css, application/javascript, application/json
    min-response-size: 1024

springdoc:
  api-docs.enabled: on

spring:
  profiles.active: local
  main.lazy-initialization: false
  datasource:
    url: ${MSSQL_DEV_URL:jdbc:sqlserver://localhost:1433;databaseName=MOB-LOCAL}
    username: ${MSSQL_DEV_USERNAME:SA}
    password: ${MSSQL_DB_KEY:Asdasdasd123}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate

external:
  error-code:
    mapper:
      accounts:
        detailCallErrorMap:
          ACC-ESB-001: SEND_EMPTY_RESPONSE
          ACC-ESB-65: EXCEEDS_WITHDRAWL_FREEQUENCY
          ACC-ESB-61: EXCEEDS_WITHDRAWL_LIMIT
      otp:
        detailcallErrorMap:
          VERIFY_OTP_4003: INVALID_SESSION_TOKEN
          VERIFY_OTP_10020: OTP_VERIFIVATION_FAILED
          VERIFY_OTP_10200: MAX_OTP_ATTEMPTS_EXCEEDED
          VERIFY_OTP_10403: MAX_OTP_FAILED_ATTEMPTS_EXCEEDED
          VERIFY_OTP_USSM_100: FAILED_TO_VERIFY_OTP
          VERIFY_OTP_USSM_101: NOT_FOUND_USER_IN_DB
          VERIFY_OTP_USSM_102: USER_BLOCKED_STATUS
          VERIFY_OTP_USSM_103: USER_INACTIVE_STATUS
          VERIFY_OTP_USSM_104: FAILED_TO_DECRYPT
          
          
  fees-code:
    mapper:
      fees:
        cardLessCashFees: '0'


logging.level:
  ROOT: warn
  # org.hibernate.type.descriptor.sql: trace
  com.mashreq: debug
esb-service:
  url: ${CDM_URL:http://172.24.70.29:7800/AllOperationsSOAP_HTTP_Service}
  app-id: ${SOAP_SERVICE_APPID:SITAPPS}
  origin-id: ${SOAP_SERVICE_ORIGINID:AE}
  connect-timeout: ${SOAP_SERVICE_CONNECTIONTIMEOUT:15000}
  read-timeout: ${SOAP_SERVICE_READTIMEOUT:30000}
  max-connection: ${SOAP_SERVICE_MAXCONNECTION:30}
  keep-alive: ${SOAP_SERVICE_KEEPALIVE:30000}

app:
  local:
    currency: 'AED'
    transaction.code: '015'
    transfer.product.id: 'DBLC'
  uae:
    address: 'UNITED ARAB EMIRATES'
    iban:
      length: 23
  bank:
    code: '033'
  loyalty:
    timeInterval: 1
    smilesProductBin: 524179
  services:
    maintenance: ${MAINTENANCE_SERVICE_URL:http://digital-dev.mashreq.com/api/maintenance-service}
    customers: ${CUSTOMER_SERVICE_URL:http://localhost:8083}
    accounts: ${ACCOUNT_SERVICE_URL:http://digital-dev.mashreq.com/api/accounts-service}
    otp: http://digital-dev.mashreq.com/api/ms-security-iam/
    cards: ${CARD_SERVICE_URL:http://digital-dev.mashreq.com/api/cards-service}
    notification: ${NOTIFICATION_SERVICE:http://digital-dev.mashreq.com/api/notification-service}
    mobcustomer: ${MOB_CUSTOMER_SERVICE:http://localhost:8088}
    beneficiary: ${BENEFICIARY_CORE_SERVICE:http://digital-dev.mashreq.com/api/beneficiary-core-service}
    mobcommon: ${MOB_COMMON_SERVICE:http://digital-dev.mashreq.com/api/mob-common-service}
  middleware:
    endpoint: http://172.24.70.29:7800/AllOperationsSOAP_HTTP_Service
    timeout: 100000
    srvMsgVersion: 1.0
    srcAppId: SITAPPS
    orgId: AE
    passPhrase: lkoiuytreaghjknvgtsfgdhelaopghen
    narration: Transfer Core Banking
    srvCode: TFT
  ftcc:
    merchantId: ${TFTCC_MERCHANT_ID:000008026734}
    terminalId: ${TFTCC_TERMINAL_ID:20091124}
    authStatus: ${TFTCC_AUTH_STATUS:A}
    amountTag: ${TFTCC_AMOUNT_TAG:TFR_AMT}
    messageThrough: ${TFTCC_MESSAGE_THROUGH:U}
    transTypeCode: ${TFTCC_TRANSFER_TYPE_CODE:FAM}
    srvCode: ${TFTCC_SERVICE_CODE:TFTCC}
    productCode: ${TFTCC_PRODUCT_CODE:PACC}
    debitAccountNo: ${TFTCC_DEBIT_ACCOUNT_NO:011099270455}
    bankReferenceNo: ${TFTCC_BANK_REFERENCE_NO:363c5a1abb}
  notification:
    email:
      AE:
        emailSubject: ${NOTIFICATION_EMAIL_SUBJECT:%s request via %s}
        fromEmailName: ${NOTIFICATION_FROM_EMAIL_NAME:MashreqDigital}
        fromEmailAddress: ${NOTIFICATION_FROM_EMAIL_ADDRESS:MashreqDigital@mashreqbank.com}
        callCenterNo: ${NOTIFICATION_EMAIL_CALL_CENTER_NO:04 424 6666}
        localFundTransfer: mt-within-own-accounts.ftl
        otherFundTransfer: mt-other-accounts.ftl
redis:
  enable: true
  write.ttl: 60
  host: localhost
  port: 6379
  timeout: 5000
  password:


mob-common:
  commonUserEventDataSource:
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    jdbcUrl: ${MSSQL_EVENT_DEV_URL:jdbc:sqlserver://localhost:1433;databaseName=MOB-LOCAL}
    username: ${MSSQL_EVENT_DEV_USERNAME:SA}
    password: ${MSSQL_EVENT_DB_KEY:Asdasdasd123}
    maxPoolSize: 40
    poolName: hikari-user-events-life-pool
    minimumidletime: 600000