management.endpoints:
  web:
    base-path: /api/actuator
    exposure.include: health

springdoc:
  api-docs:
    enabled: ${SWAGGER_ENABLED}
    path: /api-docs
  swagger-ui:
    path: /swagger

spring:
  application.name: beneficiary-core-service
  profiles.active: ${ACTIVE_PROFILE:local}
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: ${MSSQL_DEV_URL}
    username: ${MSSQL_DEV_USERNAME}
    password: ${MSSQL_DB_KEY}
  jpa:
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2012Dialect
        enable_lazy_load_no_trans: true
  main:
    banner-mode: 'off'
    lazy-initialization: false

esb-service:
  url: ${CDM_URL:http://172.24.70.29:7800/AllOperationsSOAP_HTTP_Service}
  app-id: ${SOAP_SERVICE_APPID:SITAPPS}
  origin-id: ${SOAP_SERVICE_ORIGINID:AE}
  channel: ${SOAP_SERVICE_USERID:MOMMUSER}
  connect-timeout: ${SOAP_SERVICE_CONNECTIONTIMEOUT:15000}
  read-timeout: ${SOAP_SERVICE_READTIMEOUT:30000}
  user-id: ${USER_ID:MOMMUSER}
  service-codes:
    fundTransfer: TFT
    ibanSearch: ${ACCUITYIBAN_SERVICE_CODE:QIBANVAL}
    routingCodeSearch: ${ACCUITYROUTING_SERVICE_CODE:QFAD}
    ifscSearch: ${IFSCSEARCH_SERVICE_CODE:QAXIFSC}
    flexRuleEngine: ${FLEXRULEENGINE_SERVICE_CODE:QRMTGW}
    quickRemitIndia: ${QUICK_REMIT_INDIA:TRTPTIN}
    quickRemitPakistan: ${QUICK_REMIT_INDIA:TRTPTPK}
    quickRemitInstaRem: ${QUICK_REMIT_INDIA:TINSRPMT}

external:
  error-code:
    mapper:
      accounts:
        detailCallErrorMap:
          ACC-ESB-001: SEND_EMPTY_RESPONSE
          ACC-ESB-65: EXCEEDS_WITHDRAWL_FREEQUENCY
          ACC-ESB-61: EXCEEDS_WITHDRAWL_LIMIT
      otp:
        detailcallErrorMap:
          VERIFY_OTP_4003: INVALID_SESSION_TOKEN
          VERIFY_OTP_10020: OTP_VERIFIVATION_FAILED
          VERIFY_OTP_10200: MAX_OTP_ATTEMPTS_EXCEEDED
          VERIFY_OTP_10403: MAX_OTP_FAILED_ATTEMPTS_EXCEEDED
          VERIFY_OTP_USSM_100: FAILED_TO_VERIFY_OTP
          VERIFY_OTP_USSM_101: NOT_FOUND_USER_IN_DB
          VERIFY_OTP_USSM_102: USER_BLOCKED_STATUS
          VERIFY_OTP_USSM_103: USER_INACTIVE_STATUS
  fees-code:
    mapper:
      fees:
        cardLessCashFees: '0'
  otp-code:
    mapper:
       otp:
         dpPublicKey: 1
         dpRandomNumber: 1234

app:
  local:
    currency: 'AED'
    transaction.code: '015'
    transfer.product.id: 'DBLC'
  uae:
    transaction.code: '096'
    country.iso: 'AE'
    currency.iso: '784'
    address: 'UNITED ARAB EMIRATES'
    iban:
      length: 23
  bank:
    code: '033'
  services:
    maintenance: ${MAINTENANCE_SERVICE_URL:http://maintenance-service:8080}
    customers: ${CUSTOMER_SERVICE_URL:http://customers-service:8080}
    accounts: ${ACCOUNT_SERVICE_URL:http://accounts-service:8080}
    otp: ${IAM_SERVICE_URL:http://ms-security-iam:8080}
    cards: ${CARD_SERVICE_URL:http://cards-service:8080}
    notification: ${NOTIFICATION_SERVICE:http://notification-service:8080}
    mobcustomer: ${MOB_CUSTOMER_SERVICE:http://mob-customer-service:8080}
    beneficiary: ${BENEFICIARY_CORE_SERVICE:http://beneficiary-core-service:8080}
    mobcommon: ${MOB_COMMON_SERVICE:http://mob-common-service:8080}

instarem:
  rules:
    bankCodeType:
      CA:
        code: TRANSIT NUMBER
        substr-index-before-assigning-to-routing-code: 4
      IN:
        code: IFSC CODE
      GB:
        code: SORT CODE
      LK:
        code: BRANCH CODE
      AU:
        code: BSB CODE


mob-common:
  loggers:
    logRequest: ${HTTP_DETAILS_LOG_REQUEST:true}
    logResponse: ${HTTP_DETAILS_LOG_RESPONSE:true}
    maxResponseLength: 1000
  threadPool:
    userEventAuditTaskExecutor:
      maxPoolSize: 60
      corePoolSize: 40
      queueCapacity: 100
      keepAliveSeconds: 60
      threadNamePrefix: mob-transfer-usereventlog-pool
    generalTaskExecutor:
      maxPoolSize: 30
      corePoolSize: 20
      queueCapacity: 50
      keepAliveSeconds: 60
      threadNamePrefix: mob-transfer-general-pool
  commonUserEventDataSource:
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    jdbcUrl: ${MSSQL_EVENT_DEV_URL:jdbc:sqlserver://10.196.3.22:1433;databaseName=MOB-DEV}
    username: ${MSSQL_EVENT_DEV_USERNAME:Mobdbuser}
    password: ${MSSQL_EVENT _DB_KEY:Mobdbuser}
    maxPoolSize: 40
    poolName: hikari-user-events-life-pool
    minimumidletime: 600000


redis:
  enable: true
  write.ttl: ${REDIS_TTL:60}
  host: ${REDIS_HOST:kyc-redis}
  port: ${REDIS_PORT:6379}
  timeout: ${REDIS_TIMEOUT:5000}
  password: ${REDIS_PASSWORD:P@ssword123$}

#error:
#  map:
#    ACCOUNT_BELONGS_TO_CIF: ignore
