package com.mashreq.transfercoreservice.common;
/**
 * 
 * @author SURESH
 *
 */
public interface CommonConstants {
	String SEND_EMPTY_ERROR_RESPONSE = "SEND_EMPTY_RESPONSE";
	String EXCEEDS_WITHDRAWL_FREEQUENCY = "EXCEEDS_WITHDRAWL_FREEQUENCY";
	String EXCEEDS_WITHDRAWL_LIMIT = "EXCEEDS_WITHDRAWL_LIMIT";
	String MOB_CHANNEL = "MOBILE";
	String CARD_LESS_CASH = "cardless-cash";
	String VERSION_ID = "DEF-1";
	String CHANNEL_TRACE_ID = "X-CHANNEL-TRACE-ID";
	String X_REQUEST_METADATA = "X-REQUEST-METADATA";
	String INVALID_SESSION_TOKEN = "INVALID_SESSION_TOKEN";
	String OTP_VERIFIVATION_FAILED = "OTP_VERIFIVATION_FAILED";
	String MAX_OTP_ATTEMPTS_EXCEEDED = "MAX_OTP_ATTEMPTS_EXCEEDED";
	String MAX_OTP_FAILED_ATTEMPTS_EXCEEDED = "MAX_OTP_FAILED_ATTEMPTS_EXCEEDED";
	String FAILED_TO_VERIFY_OTP = "FAILED_TO_VERIFY_OTP";
	String NOT_FOUND_USER_IN_DB = "NOT_FOUND_USER_IN_DB";
	String USER_BLOCKED_STATUS = "USER_BLOCKED_STATUS";
	String USER_INACTIVE_STATUS = "USER_INACTIVE_STATUS";
}
